### ISSUE TITLE
Download blob generated by WebCorder to disc

### ISSUE THREAD

**Issue by Yatsomi-Alt** [natsuite/WebCorder#1]
Hi there,
Thank you so much for this wonderful plugin.
As mentioned in the documents, recorder.FinishWriting() returns a path to the blob. 
I am trying to download the blob into the disc, but after testing many js functions, I'm still struggling.
Most of the answers in the web receive the blob itself and save it, not the path to the blob.
Also, Unity3D uses JSLibs to run js, so all of the JS approaches like FileSaver.js, need modification to be used within Unity3D.
I'm not a web developer and I don't know much about the JS and JSLibs. I hoped you guys can help me.
I'm Using Unity3D 2020.1.6f1 and running the build on a local web server (Servez).
Thank you so much

**Comment by olokobayusuf** [comment]
> Thank you so much for this wonderful plugin.
As mentioned in the documents, recorder.FinishWriting() returns a path to the blob.
I am trying to download the blob into the disc, but after testing many js functions, I'm still struggling.
Most of the answers in the web receive the blob itself and save it, not the path to the blob.

The common trick to download a file is to create a button, set its target URL to the blob URL (which you have), and manually 'click' it from code. [You don't need the blob itself](https://stackoverflow.com/questions/30864573/what-is-a-blob-url-and-why-it-is-used).

> Also, Unity3D uses JSLibs to run js, so all of the JS approaches like FileSaver.js, need modification to be used within Unity3D.
I'm not a web developer and I don't know much about the JS and JSLibs. I hoped you guys can help me.

I'm not very familiar with integrating Unity with JS libraries either. At a minimum though you will need to familiarize yourself with it to be able to modify and extend Unity's WebGL output to add your custom functionality.
