### ISSUE TITLE
Facing issue in video save

### ISSUE THREAD

**Issue by Tborth** [natsuite/WebCorder#2]
Video doesn't save to the device after the record my android version is 11

**Comment by olokobayusuf** [comment]
Hey there, are you using NatCorder or WebCorder? If NatCorder, then [email us](mailto:hi@natsuite.io) instead of opening an issue on this repo. NatCorder never saves recordings to the camera roll. You have to copy the recording with a sharing plugin like NatShare.

**Comment by Tborth** [comment]
Yes I am using netcoder /webcoder scene
How can I save it with netshare can you help please 🙏

**Comment by olokobayusuf** [comment]
@Tborth [check out the docs](https://docs.natsuite.io/natcorder/integrations/social-sharing).

**Comment by Tborth** [comment]
Sir can you help how can I switch camer rear to front in android device?

**Comment by olokobayusuf** [comment]
[See this answer on StackOverflow](https://stackoverflow.com/questions/66144356/how-to-select-front-camera-from-device-in-unity).

**Comment by Tborth** [comment]
Thanks sir 🙏
